<a href="https://colab.research.google.com/github/pauloladapo13/DLearning/blob/master/NumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
array1 = np.array([[10, 20, 30], [40, 50, 50], [70, 80, 90]])
print(array1)

zero_arr1 = np.zeros(5)
print(zero_arr1)
print('\n**********************************')

zero_arr2= np.zeros((4,4))
print(zero_arr2)

print("\n********************************")
one_arr1= np.ones(4)
print(one_arr1)
print("\n****************************")

one_arr2 = np.ones((3,2), dtype= int)
print(one_arr2)

print("\n**************************")

rand_arr = np.random.rand(5,4)
print(rand_arr)

print("\n**************************")


iden_arr1 = np.eye(4)
print(iden_arr1)

print("\n**************************")


iden_arr2= np.eye(2, dtype= int)
print(iden_arr2)

print("\n**************************")

a = np.arange(12).reshape(3, 4)
print(a)

rows = np.array([False, True, True])
a=a[rows, : ]
print(a)

em= pd.DataFrame({"weight": pd.Series([60, 80, 100], index=["Ram", "Sam", "Max"]), "dob": pd.Series([1990,1970,1991], index=["Ram", "Max", "Sam"], name="year"), "hobby": pd.Series(["Reading", "Singing"], index=["Ram ", "Max"])})
print(em)
# head(n) or tail(n); to display the top
# info(): to display information
# describe(): to display handy aggregate and statistical information


[[10 20 30]
 [40 50 50]
 [70 80 90]]
[0. 0. 0. 0. 0.]

**********************************
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

********************************
[1. 1. 1. 1.]

****************************
[[1 1]
 [1 1]
 [1 1]]

**************************
[[0.31347986 0.30965019 0.50392807 0.50972475]
 [0.71149336 0.19923975 0.19183648 0.83872739]
 [0.5809474  0.52530647 0.87954295 0.33500367]
 [0.86159052 0.68471306 0.34631266 0.90345846]
 [0.03452668 0.77540006 0.7258586  0.97301765]]

**************************
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

**************************
[[1 0]
 [0 1]]

**************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
      weight     dob    hobby
Max    100.0  1970.0  Singing
Ram     60.0  1990.0      NaN
Ram      NaN     NaN  Reading
Sam     80.0  1991.0      NaN
